name: Build Latex
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26

      - run: nix build

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          path: |
            result/*.pdf
            LICENSE
            README.md
